### ISSUE TITLE
manual_qc table contains more rows than sites table

### ISSUE THREAD

**Issue by tischi** [mobie/covid-if-project#5]
@constantinpape 

I am working on this: https://github.com/mobie/mobie-viewer-fiji/issues/748

I selected the `manual_qc` table:
https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/sites/manual_qc.tsv

Is it OK that manual_qc` contains more rows than the table into which it should be merged?

<img width="519" alt="image" src="https://user-images.githubusercontent.com/2157566/169848875-77cf8d56-25af-4092-90eb-45849311b28d.png">

**Comment by tischi** [comment]
The log of MoBIE for this looks like that now:

```
Read in 174 ms: https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/sites/default.tsv
Opened view: default, in 15845 ms.
 
Opening table:
https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/sites/manual_qc.tsv
[WARNING] There were 846 rows that were only present in the additional table.
```

Does that make sense? Before I was throwing an error when that happened....

**Comment by constantinpape** [comment]
That looks better!
But it's weird that it contains more columns, since I have saved it with MoBIE...
Maybe another bug? I will look into it and create a separate issue if yes.

**Comment by tischi** [comment]
Not sure it is a bug.
Maybe `default.tsv` in fact contains more rows, but we only load the ones that are actually occurring in the annotated regions? I think we had some logic like this...

**Comment by constantinpape** [comment]
ok, I will check. Could you make a new MoBIE-beta release so I can load the region columns?

**Comment by tischi** [comment]
done

**Comment by constantinpape** [comment]
Hey @tischi,
everything works with the new MoBIE-beta release, thanks!

I also checked the tables, and the columns are exactly the same in both tables! Also note that there are 864 rows, so this: 
`[WARNING] There were 846 rows that were only present in the additional table.` suggests that the matching you do fails completely.

And fyi here's the code to check this in python:
```py
import numpy as np
import pandas as pd
default = pd.read_csv("./data/20200406_164555_328/tables/sites/default.tsv", sep="\t")
manual_qc = pd.read_csv("./data/20200406_164555_328/tables/sites/manual_qc.tsv", sep="\t")
ids1 = default["region_id"].values
ids2 = manual_qc["region_id"].values
print(len(ids1))
print(len(ids2))
print(np.setdiff1d(ids1, ids2))
```
```
864
864
[]
```
(if there were different columns the setidiff would return values).

But note that the column is loaded correctly, with correct matching of the rows (i.e. values are associated with the correct sites); so I am not sure what's going on on your end; maybe just an issue with the logging?

Anyway, I will leave this open in case you want to figure it out; but not a high priority from my side, since everything works as expected for me.

**Comment by tischi** [comment]
I think it makes sense. Have a look at the screenshot of the table at my first post of this issue. It has `18` rows. `846 + 18 = 864`. 

So my theory is, as mentioned above, that the `default` view only shows 18 sites (=images), thus only 18 rows of `default.tsv` _are read into the display table_ (In MoBIE lingo: there are only `18 TableRow` in RAM).  Consequently, when matching `manual_qc.tsv` to that subset of `18 TableRow` `846` don't match, because `846` sites are not shown (and thus are not in the table, and thus cannot be matched).

**Comment by constantinpape** [comment]
Ah ok, now I see. Yes; it makes sense if you load it with the default view. It's meant to be loaded with the full grid view.
I think everything works exactly as expected now.
